chronos:
  image: rancher/chronos:latest
  environment:
    MESOS_SERVICE: ${MESOS_SERVICE}
    ZK_SERVICE: ${ZK_SERVICE}
    CHRONOS_HTTP_PORT: ${CHRONOS_HTTP_PORT}
  ports:
  - "${CHRONOS_HTTP_PORT}:${CHRONOS_HTTP_PORT}"