name: Zookeeper
description: |
  Maintain configuration information, naming, provide 
  distributed synchronization and group services
version: 3.4.6-rancher2
category: System
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.56.0
license: 
