name: Traefik
description: |
  Traefik active load balancer
version: v1.5.3-rancher1
category: Load Balancing
maintainer: "Raul Sanchez <rawmind@gmail.com>"
license:
projectURL: https://github.com/rawmind0/alpine-traefik
