postgres:
    image: postgres

taigaback:
    image: ipedrazas/taiga-back
    links:
        - postgres:postgres
    ports:
        - "8000:8000"

taigafront:
    image: ipedrazas/taiga-front
    links:
        - taigaback:taiga-back
    ports:
        - "80:80"
    environment:
        - "API_NAME=boot2docker"
