name: Rancher Backup
description: |
  It's a general purpose to solve backup matter on Rancher.
version: 2.0.1
category: Backup
maintainer: "Sebastien Langoureaux <linuxworkgroup@gmail.com>"
license: MIT License
