name: Apache Kafka
description: |
  (Experimental) Kafka cluster
version: 0.9.0-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.56.0
license: 
