marathon:
  image: rancher/marathon:latest
  environment:
    ZK_SERVICE: Mesos/zookeeper
    MESOS_SERVICE: Mesos/mesos-master
    MARATHON_HTTP_PORT: ${MARATHON_HTTP_PORT}
  ports:
  - "${MARATHON_HTTP_PORT}:${MARATHON_HTTP_PORT}"
  cap_add:
  - NET_ADMIN