alfresco:
  environment:
    CIFS_ENABLED: 'false'
    FTP_ENABLED: 'false'
  labels:
    io.rancher.sidekicks: alfresco-data
  tty: true
  image: webcenter/rancher-alfresco:v5.1-201605-1
  links:
  - postgres:db
  stdin_open: true
  ports:
  - 8080:8080/tcp
alfresco-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
  - /opt/alfresco/alf_data
  net: none
postgres:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: ${database_name}
    POSTGRES_PASSWORD: ${database_password}
    POSTGRES_USER: ${database_user}
  labels:
    io.rancher.sidekicks: postgres-data
  tty: true
  image: postgres:9.4
  stdin_open: true
postgres-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: alpine
  volumes:
  - /var/lib/postgresql/data/pgdata
  net: none
