scheduler:
  image: rancher/elasticsearch:latest
  environment:
    ZK_SERVICE: Mesos/zookeeper
    MESOS_SERVICE: Mesos/mesos-master
    SCHEDULER_PORT: ${SCHEDULER_PORT}
    JAVA_OPTS: -Xms256M -Xmx256M
    NODE_COUNT: ${NODE_COUNT}
  ports:
  - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
