version: '2'
services:
  filebeat:
    image: eason02/filebeat-alpine:5.6.3
    container_name: filebeat-alpine-5.6.3
    restart: always
    environment:
      - env=${ENV}
      - logstash=${LOGSTASH}
      - project=${PROJECT}
    network_mode: host
    volumes:
      - /var/lib/filebeat/:/filebeat/data
      - ${APPLOG_PATH}:/home/user/:ro
      - ${NGINXLOG_PATH}:/var/log/nginx/:ro
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
